### ISSUE TITLE
Unclear as to what user needs to do what

### ISSUE THREAD

**Issue by its-vincent** [maldua/zimbra-foss-builder#2]
Hi, 

I have tried to use your build scripts to make a Dockerfile for Rocky 8, but I am confused as to what needs to be done as what user. 

in the README.md it says the builder setup should be run as 

`docker build \
  --build-arg ZIMBRA_BUILDER_UID=$(id -u) \
  --build-arg ZIMBRA_BUILDER_GID=$(id -g) \
  --tag zimbra-smart-rocky-8-builder . \
  -f Dockerfile-smart-rocky-8
`
If I run this as root it fails because $(id -u) returns the root userid, 0, and userid 0 already exists. 

However, if I run it as a different, non-sudo user, then the command in the Dockerfile 

`    && echo build_user ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/build_user \
`
will fail as I will not have permission to look in the /etc/sudoers.d folder. 

It also comaplain that the ZM_BUILD_RELEASE_NO agrument hasn't been supplied. 

Can you please  update the README.md file to make it more clear as to how to perform the steps. 

Thanks,
Vincent

**Comment by its-vincent** [comment]
Below is the content of  Dockerfile-smart-rocky-8 


`FROM rockylinux:8

ARG ZIMBRA_BUILDER_UID
ARG ZIMBRA_BUILDER_GID
ARG ZM_BUILD_RELEASE_NO

# Some ideas were taken from: https://github.com/Zimbra/zm-base-os

# Update mirrors
RUN sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/Rocky-PowerTools.repo

# SYSTEM
RUN yum clean all
RUN yum upgrade -y
RUN yum install -y curl wget which
RUN yum install -y sudo

# ENVIRONMENT
RUN yum install -y git perl ruby
RUN yum install -y perl-Data-Dumper perl-IPC-Cmd
RUN yum install -y gcc gcc-c++ make
RUN yum install -y java-1.8.0-openjdk maven
RUN yum install -y rpm-build createrepo rsync
RUN yum install -y ant-junit junit hamcrest-core

# USER
RUN groupadd --gid ${ZIMBRA_BUILDER_GID} build \
    && useradd --uid ${ZIMBRA_BUILDER_UID} --gid ${ZIMBRA_BUILDER_GID} -m build \
    && echo build ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/build \
    && chmod 0440 /etc/sudoers.d/build \
    && mkdir -p /home/build/installer-build \
    && chown -R ${ZIMBRA_BUILDER_UID}:${ZIMBRA_BUILDER_GID} /home/build

USER build
WORKDIR /home/build
CMD /usr/local/zimbra-foss-builder/zimbra-smart-builder.sh ${ZM_BUILD_RELEASE_NO}`

**Comment by adriangibanelbtactic** [comment]
Regarding Rhel 8 binaries (which should support installing onto Rocky Linux 8 seamlessly) there are already provided thanks to `rhel-8` files which use Centos 8 under the hood for the build.

You can download them from the [Maldua's Zimbra Foss Builds Downloads Page](https://maldua.github.io/zimbra-foss-builder/downloads.html) if you do not want to build them yourself.

**Comment by adriangibanelbtactic** [comment]
> Hi,
> 
> I have tried to use your build scripts to make a Dockerfile for Rocky 8, but I am confused as to what needs to be done as what user.
> 
> in the README.md it says the builder setup should be run as
> 
> `docker build \ --build-arg ZIMBRA_BUILDER_UID=$(id -u) \ --build-arg ZIMBRA_BUILDER_GID=$(id -g) \ --tag zimbra-smart-rocky-8-builder . \ -f Dockerfile-smart-rocky-8 ` If I run this as root it fails because $(id -u) returns the root userid, 0, and userid 0 already exists.
> 
> However, if I run it as a different, non-sudo user, then the command in the Dockerfile
> 
>```
> && echo build_user ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/build_user \
>```
> will fail as I will not have permission to look in the /etc/sudoers.d folder.

That's not how Docker works. If you use an user that it's part of the docker group the build process ( `docker build` ) will be run as root.

It's later on when you run `docker run` that the USER statement from the Dockerfile file will be used and the `build` user will be used within the Docker instance (mapped to your regular user uid and gid).

In that run step the sudoers.d file has been already created and `build` user will be able to run sudo commands without a password.

**Comment by adriangibanelbtactic** [comment]
> It also complain that the ZM_BUILD_RELEASE_NO agrument hasn't been supplied.

Is it a warning or the program stops altogether ?
If it is a warning we should document that that's to be expected and it can be ignored.

I have not tested the smart Dockerfiles recently as what I am most interested are the manual builds and the github ones.

When you build the Docker `ZM_BUILD_RELEASE_NO` is not used at all because the `CMD` is not run so you it's not a compulsory thing to use, another thing is when you run the docker but there is another command for that.

I cannot test an smart Dockerfile build as per the README.md documentation right now but I will do it later on.

In any case if, whatever the reason is, the docker build step needs to have that `ZM_BUILD_RELEASE_NO` variable filled it is just changing from:

```
docker build \
  --build-arg ZIMBRA_BUILDER_UID=$(id -u) \
  --build-arg ZIMBRA_BUILDER_GID=$(id -g) \
  --tag zimbra-smart-ubuntu-20.04-builder . \
  -f Dockerfile-smart-ubuntu-20.04
```
to:
```
docker build \
  --build-arg ZIMBRA_BUILDER_UID=$(id -u) \
  --build-arg ZIMBRA_BUILDER_GID=$(id -g) \
  --build-arg ZM_BUILD_RELEASE_NO=NonUsed \
  --tag zimbra-smart-ubuntu-20.04-builder . \
  -f Dockerfile-smart-ubuntu-20.04
```
.

**Comment by adriangibanelbtactic** [comment]
> I do want to build them myself.

If you want to build something that its result can be installed in Rocky Linux 8 you should be using the already provided `Dockerfile-smart-rhel-8` which uses Centos 8 under the hood for doing the build.

Thanks to Docker abstraction you can build this version from a Rocky Linux 8 distribution with docker installed.

If you actually want that the Docker instance builds everything within a Rocky Linux 8 OS instead of the current Centos 8 then, yes, you are supposed to add your own `Dockerfile-rocky-rhel-8` as you were trying.

**Comment by adriangibanelbtactic** [comment]
Let's do a test with one user that I have already setup for these builds so that you can get the full picture.

```
mkdir ~/vincent-test
cd ~/vincent-test
```

```
git clone https://github.com/maldua/zimbra-foss-builder
cd zimbra-foss-builder
```

```
docker build \
  --build-arg ZIMBRA_BUILDER_UID=$(id -u) \
  --build-arg ZIMBRA_BUILDER_GID=$(id -g) \
  --tag zimbra-smart-rhel-8-builder . \
  -f Dockerfile-smart-rhel-8
```

Please note that at this point for me it does not complain about `ZM_BUILD_RELEASE_NO` being missing as you seem to suggest. Just in case it's relevant: `docker --version` says for me: `Docker version 20.10.12, build e91ed57`.

```
docker run \
  -it \
  --env ZIMBRA_BUILDER_UID=$(id -u) \
  --env ZIMBRA_BUILDER_GID=$(id -g) \
  --env ZM_BUILD_RELEASE_NO='10.0.7' \
  -v ~/.ssh:/home/build/.ssh:ro \
  -v $(pwd):/usr/local/zimbra-foss-builder:ro \
  -v $(pwd)/BUILDS:/home/build/installer-build/BUILDS:rw \
  zimbra-smart-rhel-8-builder:latest
```

And later on... if dns resolution is not bugging me out inside of the Docker I should find the results under the `BUILDS` folder where a filename similar to `zcs-10.0.7_GA_10.0.7_maldua_1000.RHEL8_64.20240331160936.tgz` will appear on one of its subdirectories.

**Comment by adriangibanelbtactic** [comment]
> Can you please update the README.md file to make it more clear as to how to perform the steps.

Can you please give me feedback on this [improved README.md](https://github.com/maldua/zimbra-foss-builder/blob/267bac04825d58bc83b56b91d3911b4b378c6d25/README.md) ?

Is there something that you would improve or reword?

Once we are happy with it I will of course merge it onto the main branch so that it's the default when you enter the repo.

Thank you very much!

**Comment by its-vincent** [comment]
I think I found the issue. 

Installing "docker" on Rocky defaults to installing podman (which emulates docker). The setup is not the same. 

I found a tutorial on the web for installing "docker-ce" from the docker repos, and once I installed that, following your instructions seem to work correctly.  

Currently building 10.0.6 as a test ...

**Comment by adriangibanelbtactic** [comment]
> Installing "docker" on Rocky defaults to installing podman (which emulates docker). The setup is not the same.

I wasn't aware of Red Hat hijacking the docker package name in order to install another piece of software by default. I guess we will have to add a big warning on making sure to use *docker-ce* instead.

If you think it's worth rewriting some of the Dockerfiles so that they are podman compatible I don't mind that but, you know, I was very proud of these docker calls so that you don't have to resort to root user in order to be able to read, modify or delete the final BUILDS folder.

Keep us updated on your tests so that we can focus finally on polishing the documentation for newcomers.

Thank you!

**Comment by adriangibanelbtactic** [comment]
> > Can you please update the README.md file to make it more clear as to how to perform the steps.
> 
> Can you please give me feedback on this [improved README.md](https://github.com/maldua/zimbra-foss-builder/blob/267bac04825d58bc83b56b91d3911b4b378c6d25/README.md) ?
> 
> Is there something that you would improve or reword?
> 
> Once we are happy with it I will of course merge it onto the main branch so that it's the default when you enter the repo.
> 
> Thank you very much!

I've pushed this and some additional commit to main branch. You can now comment on what's on the public repo main page directly.

**Comment by adriangibanelbtactic** [comment]
Documentation regarding docker was improved.
No more feedback was received in a long time.

I'm closing the issue.
